#!/usr/bin/env bash
# this is a bash script that
#   displays numbers 1 to 100
# then displays
#   FizzBuzz when the number is a multiple of 3 and 5
#   Fizz when the number is a multiple of 3
#   Buzz when the number is a multiple of 5
# else it displays a number: all this in list format

i=1
while [ $i -le 100 ]
do
    echo $i
    if [ $i/3=0 && $i/5=0 ];
    then
        echo "FizzBuzz"
    elif [ $i/3 ];
    then
        echo "Fizz"
    else
        echo "Buzz"
    fi
    i=$((i+1))
    
done