#!/usr/bin/env bash
#This is a bash script that displays "Best School" 10 times
#but for the 9th iteration display "Best School" and 
#then prints "Hi" on a new line

i=0
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
    i=$((i+1))
done
