#!/usr/bin/env bash
# This is a bash script that loops from 1 to 10 and:
# display "bad luck" in the 4th loop iteration
# display "good luck" in the 8th loop iteration
# display "Best School" in all the other iterations
# using a while loop and if, elif and else statement

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done