#!/usr/bin/env bash
# this is a bash script that:
#   gives information about the school file
#   uses an if and else statement
# then checks if the file exists and prints
#   if the file exists "school file exists"
#   if the file does not exist "School file does not exist"
# if the file exists
#   if the file is empty "school file is empty"
#   if the file is not empty "school file is not empty"
#   if the file is a regular file "school is a regular file"
#   if the file is not a regular file then do nothing

if [ -e "school" ]; then
    echo "school file exists"

    if [ -s "school" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "school" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi